name: Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python']


    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
          cmake \
          glslang-tools \
          libglfw3-dev \
          libglm-dev \
          libstb-dev \
          libvulkan-dev \
          python3 \

    - name: Build dependencies
      run: |
        cd libs/tinyobjloader
        cmake -B bin -DCMAKE_BUILD_TYPE=Release
        cmake --build bin -j$(nproc)
        cd bin; sudo make install -j$(nproc)
        cd ../../../

    - name: Build
      run: |
        cmake -B bin -DCMAKE_BUILD_TYPE=Release
        cmake --build bin -j$(nproc)

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"