name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python']


    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
          cmake \
          glslang-tools \
          libglfw3-dev \
          libglm-dev \
          libstb-dev \
          libvulkan-dev \
          python3 \
          python3-pip \
          uncrustify \
        
        sudo snap install go --classic
        sudo snap install shfmt

        pip install black cmakelang

        npm install -g prettier

        go install github.com/google/yamlfmt/cmd/yamlfmt@latest

    - name: Build dependencies
      run: |
        git clone --recursive https://github.com/Koihik/LuaFormatter.git
        cd LuaFormatter
        cmake -B bin -DCMAKE_BUILD_TYPE=Release
        cmake --build bin -j$(nproc)
        cd bin
        sudo make install -j$(nproc)
        cd ../../
        rm -fr LuaFormatter

        cd libs/tinyobjloader
        cmake -B bin -DCMAKE_BUILD_TYPE=Release
        cmake --build bin -j$(nproc)
        cd bin; sudo make install -j$(nproc)
        cd ../../../

    - name: Format
      run: |
        python3 src/scripts/format.py

    - name: Build
      run: |
        cmake -B bin -DCMAKE_BUILD_TYPE=Release
        cmake --build bin -j$(nproc)

    - name: Run
      run: |
        cd bin; ./TEMPORARYNAMEHEADLESS; cd ../
  
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        add_options: '-A'
        commit_message: 'Automated changes!'